### ISSUE TITLE
[BUG] can't load config client.conf: No such file or directory

### ISSUE THREAD

**Issue by wanjohiryan** [gmbeard/shadow-cast#30]
Sorry for bothering you again.

I am so close to making it work, I can feel it. But after updating my drivers and CUDA, i have ran into a new issue:

<img width="603" alt="2024-04-17 13_02_55-ubuntu@990deeb7e8b3_ ~" src="https://github.com/gmbeard/shadow-cast/assets/71614375/927a4996-5c57-46ee-bd27-5bf0d9e2e2cf">

And from a quick search on Google, it has something to do with pipewire, no?

Do I need to install pipewire to run `shadow-cast`? 

Is there a way to run with pulseaudio instead? 

Thank you for your help :)

**Comment by wanjohiryan** [comment]
Update: I have successfully installed pipewire, now I get the error: 

`Couldn't connect stream` ... Very informative :)

I think it has something to do with how am running pipewire

**Comment by gmbeard** [comment]
Yes, Pipewire is a strict runtime dependency. Shadow Cast won't work without it.

I can't really provide support with your Pipewire setup, I'm afraid; It can vary between DEs / distros.

It it helps, this is how I start Pipewire in my `.xinitrc` but YMMV ...

```
if test -z "$DBUS_SESSION_BUS_ADDRESS"; then
    eval $(dbus-launch --sh-syntax --exit-with-session)
fi

pids=()
for p in pipewire wireplumber pipewire-pulse; do
    $p &
    pids+=($!)
done

kill_bg() {
    for p in ${pids[@]}; do
        kill $p
    done
}

trap kill_gb EXIT INT TERM
```
