### ISSUE TITLE
Unable to build on Fedora 40

### ISSUE THREAD

**Issue by SleepingPanda** [gmbeard/shadow-cast#34]
Hi there, Fedora 40 is unable to build shadow-cast.

```
-- The CXX compiler identification is GNU 14.1.1
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Defaulting CMAKE_BUILD_TYPE to Release
-- IPO supported. Enabling
-- Found PkgConfig: /usr/bin/pkg-config (found version "2.1.1") 
-- Pipewire_INCLUDE_DIR: /usr/include/pipewire-0.3
-- Pipewire_LIBRARY: /usr/lib64/libpipewire-0.3.so
-- SPA_INCLUDE_DIR: /usr/include/spa-0.2
-- Components: avcodec;avdevice;avfilter;avformat;avutil;swresample;swscale
CMake Error at cmake/FindFFMpeg.cmake:94 (message):
  FFMpeg: Not all required components could be found
Call Stack (most recent call first):
  CMakeLists.txt:44 (find_package)


-- Configuring incomplete, errors occurred!
```

Can you tell me how to proceed?

**Comment by gmbeard** [comment]
@SleepingPanda looks like the build config step is failing to find the ffmpeg dependencies. Have you installed the ffmpeg development package?

**Comment by gmbeard** [comment]
Yes, the `ffmpeg-free-devel` pacakge (and its dependencies) appear to provide the required headers. There's possibly a bug in Shadow Cast's configure step in that case.

Any chance you could paste the output of the following command?...

```
$ pkg-config --variable=includedir libavcodec
```

**Comment by gmbeard** [comment]
Ok, I think this is a silly typo bug on my part :facepalm: 

If you're able to apply it then the following patch _should_ fix it...

```diff
diff --git a/cmake/FindFFMpeg.cmake b/cmake/FindFFMpeg.cmake
index 89914bb..0f60fa0 100644
--- a/cmake/FindFFMpeg.cmake
+++ b/cmake/FindFFMpeg.cmake
@@ -11,7 +11,7 @@ function(try_find_ffmpeg_targets)
     )
 
     foreach(FFMPEG_COMPONENT ${EXPORT_FFMPEG_NAMES})
-        pkg_check_modules(PC_${FFMPEG_COMPONENT}_CODEC QUIET "lib${FFMPEG_COMPONENT}")
+        pkg_check_modules(PC_${FFMPEG_COMPONENT} QUIET "lib${FFMPEG_COMPONENT}")
 
         find_path(FFMpeg_${FFMPEG_COMPONENT}_INCLUDE_DIR
             NAMES ${FFMPEG_COMPONENT}.h
```

You will have to reconfigure the project again after applying the patch, by either removing your `./build` directory, or by running the following...

```
$ cd ./build
$ cmake --fresh ..
```

If this works then I will apply the fix upstream

**Comment by gmbeard** [comment]
Great! Thank you for helping with that :+1:

**Comment by gmbeard** [comment]
Looks like the EGL headers can't be found. What does the following show?...

```
$ pkg-config --variable=includedir egl
```

**Comment by gmbeard** [comment]
I believe it's provided by `libglvnd-devel`. This probably needs adding to the README

**Comment by gmbeard** [comment]
That's great. Nice work. I suspect these pkgs are pulled in as dependencies of other pkgs on my system. I shall get these added to the README. Thank you for persevering :+1:

**Comment by gmbeard** [comment]
No problem at all. I don't really have access to multiple distros to test these kinds of things, so this feedback is very welcome

**Comment by gmbeard** [comment]
Hi @SleepingPanda,

You're asking shadow-cast to use an audio encoder called `ffmpeg` here, which isn't a valid/available encoder name. You can get a list of the available audio encoders using the following command...

```sh
$ ffmpeg -encoders | grep -E '^ A'
```

On my system, this shows ...

```
 A..... = Audio
 A....D aac                  AAC (Advanced Audio Coding)
 A....D ac3                  ATSC A/52A (AC-3)
 A....D ac3_fixed            ATSC A/52A (AC-3) (codec ac3)
 A....D adpcm_adx            SEGA CRI ADX ADPCM
 A....D adpcm_argo           ADPCM Argonaut Games
 A....D g722                 G.722 ADPCM (codec adpcm_g722)

(... continued> ...)
```

The valid names you can use with the `shadow-cast -A` option are listed in the second column (after the `A...D` column)

_NOTE_: I haven't exhaustively tested all these audio encoders so YMMV. Also note this from the README about the sample rate...

> (NOTE: Some encoders will only support certain sample rates. Shadow Cast will display an error if your chosen sample rate isn't supported)
